export const dogs: string[] = ['Affenpinczer',
  'Aidi',
  'Akita Amerykańska',
  'Akita',
  'Appenzeller',
  'Basset Artezyjsko-Normandzki',
  'Basset Bretoński',
  'Basset Gaskoński',
  'Basset Hound',
  'Beagle Harrier',
  'Beagle',
  'Bearded Collie',
  'Bedlington Terier',
  'Bernardyn',
  'Bokser',
  'Bolończyk',
  'Border Collie',
  'Brabantczyk',
  'Buldog Amerykański',
  'Buldog Angielski',
  'Buldog Francuski',
  'Bulmastif',
  'Bulterier Miniaturowy',
  'Bulterier',
  'Charcik Włoski',
  'Chart Afgański',
  'Chart Afrykański',
  'Chart Arabski',
  'Chart Hiszpański',
  'Chart Kirgiski',
  'Chart Perski',
  'Chart Polski',
  'Chart Rosyjski',
  'Chart Szkocki',
  'Chart Węgierski',
  'Chart Środkowoazjatycki',
  'Chin Japoński',
  'Cocker Spaniel Amerykański',
  'Cocker Spaniel Angielski',
  'Czarnogórski Gończy Górski',
  'Dalmatyńczyk',
  'Dandie Dinmont Terier',
  'Doberman',
  'Dog Argentyński',
  'Dog Kanaryjski',
  'Dog Niemiecki',
  'Dog Z Bordeaux',
  'Dog Z Majorki',
  'Dowodny Portugalski',
  'Dowodny Spaniel Irlandzki',
  'Elkhund Czarny',
  'Elkhund Szary',
  'Fiński Lapphund',
  'Foksterier Krótkowłosy',
  'Foksterier Szorstkowłosy',
  'Foxhound Amerykański',
  'Foxhound Angielski',
  'Fryzyjski Pies Dowodny',
  'Gończy Alpejski Krótkonożny',
  'Gończy Bałkański',
  'Gończy Chorwacki',
  'Gończy Fiński',
  'Gończy Hamiltona',
  'Gończy Hiszpański',
  'Gończy Mały Gaskoński',
  'Gończy Niemiecki',
  'Gończy Polski',
  'Gończy Schillera',
  'Gończy Smalandzki',
  'Gończy Szwajcarski',
  'Gończy Słowacki',
  'Gończy Węgierski',
  'Gryfon Korthalsa',
  'Gryfonik Belgijski',
  'Grzywacz Chiński',
  'Górski Pirenejski',
  'Inne',
  'Hawańczyk',
  'Hovawart',
  'Husky Syberyjski',
  'Jamnik',
  'Jindo',
  'Karelski Pies Na Niedźwiedzie',
  'Komondor',
  'Kundel',
  'Landseer',
  'Leonberger',
  'Lwi Piesek',
  'Maltańczyk',
  'Mastif Angielski',
  'Mastif Hiszpański',
  'Mastif Japoński',
  'Mastif Neapolitański',
  'Mastif Pirenejski',
  'Mastif Tybetański',
  'Mops',
  'Moskiewski Stróżujący',
  'Myśliwski Niemiecki Terier',
  'Niebieski Spaniel Pikardyjski',
  'Nowofundland',
  'Ogar Polski',
  'Owczarek Anatolijski',
  'Owczarek Australijski (Typ Amerykański)',
  'Owczarek Australijski – Kelpie',
  'Owczarek Belgijski',
  'Owczarek Biały Szwajcarski',
  'Owczarek Chorwacki',
  'Owczarek Francuski Beauceron',
  'Owczarek Francuski Briard',
  'Owczarek Holenderski',
  'Owczarek Kataloński',
  'Owczarek Kaukaski',
  'Owczarek Kraski',
  'Owczarek Niemiecki',
  'Owczarek Pikardyjski',
  'Owczarek Pirenejski',
  'Owczarek Pirenejski',
  'Owczarek Podhalański',
  'Owczarek Polski Nizinny',
  'Owczarek Portugalski[',
  'Owczarek Staroangielski',
  'Owczarek Szetlandzki',
  'Owczarek Szkocki Długowłosy',
  'Owczarek Szkocki Krótkowłosy',
  'Owczarek Z Bergamo',
  'Owczarek Z Majorki',
  'Owczarek Środkowoazjatycki',
  'Pasterski Australijski',
  'Pasterski Berneński',
  'Pasterski Duży Szwajcarski',
  'Pasterski Słowacki',
  'Pekińczyk',
  'Pies Chodzki',
  'Pies Faraona',
  'Pies Grenlandzki',
  'Pies Kananejski',
  'Pies Z Maremmy I Arbuzzów',
  'Pinczer Austriacki',
  'Pinczer Miniaturowy',
  'Pinczer Średni',
  'Pit Bull Amerykański  Terrier',
  'Podenco Z Ibizy',
  'Podengo Portugalski',
  'Pointer',
  'Posokowiec Bawarski',
  'Posokowiec Hanowerski',
  'Pudel',
  'Płochacz Niemiecki',
  'Retriever Z Nowej Szkocji',
  'Rottweiler',
  'Samojed',
  'Sarplaninac',
  'Seter Angielski',
  'Seter Irlandzki',
  'Seter Szkocki',
  'Spaniel Amerykański Dowodny',
  'Spaniel Francuski',
  'Spaniel Kontynentalny Miniaturowy',
  'Spaniel Pikardyjski',
  'Spaniel Pont-Audemer',
  'Spaniel Tybetański',
  'Springer Spaniel Angielski',
  'Springer Spaniel Walijski',
  'Staffordshire Amerykański  Terrier',
  'Staghound Amerykański ',
  'Stróżujący Portugalski',
  'Sznaucer Miniaturowy',
  'Sznaucer Olbrzym',
  'Sznaucer Średni',
  'Szpic Fiński',
  'Szpic Islandzki Pasterski',
  'Szpic Japoński',
  'Szpic Niemiecki',
  'Szpic Nordycki',
  'Szpic Włoski',
  'Szwedzki Lapphund',
  'Szwedzki Vallhund',
  'Terier Australijski',
  'Terier Brazylijski',
  'Terier Czarny Rosyjski',
  'Terier Czeski',
  'Terier Irlandzki',
  'Terier Japoński',
  'Terier Silky Australijski',
  'Terier Szkocki',
  'Terier Tybetański',
  'Terier Walijski',
  'Terrier Border',
  'Terrier Boston',
  'Toy Amerykański Terier',
  'Wilczak Czechosłowacki',
  'Wilczarz Irlandzki',
  'Wodny Hiszpański',
  'Wyżeł Duński',
  'Wyżeł Fryzyjski',
  'Wyżeł Gaskoński',
  'Wyżeł Hiszpański Z Burgos',
  'Wyżeł Niemiecki Długowłosy',
  'Wyżeł Niemiecki Krótkowłosy',
  'Wyżeł Niemiecki Ostrowłosy',
  'Wyżeł Niemiecki Szorstkowłosy',
  'Wyżeł Pirenejski',
  'Wyżeł Portugalski',
  'Wyżeł Weimarski',
  'Wyżeł Węgierski Krótkowłosy',
  'Wyżeł Węgierski Szorstkowłosy',
  'Wyżeł Włoski Krótkowłosy',
  'Wyżeł Włoski Szorstkowłosy',
  'Łajka Jakucka',
  'Łajka Karelo-Fińska',
  'Łajka Rosyjsko-Europejska',
  'Łajka Wschodniosyberyjska',
  'Łajka Zachodniosyberyjska'];
