import { IDog } from "src/app/models/sample";

export class DogsMockedData {

    public static Dogs: Array<IDog> = [
        {
            "id": "1",
            "name": "Puszek",
            "imgUrl": "http://www.channel4.com/media/images/Channel4/c4-news/2013/Aug/06/06_Dogs_r_w.jpg",
            "status": "Niedostepny",
            "available": false,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Poznań",
            "ownerId": 1
        },
        {
            "id": "2",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "age": 1,
            "gender": "Pies",
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1

        },
        {
            "id": "3",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "4",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "5",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "6",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "7",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "8",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "9",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "10",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "11",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "12",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "13",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "14",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "15",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "16",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "17",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "18",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "19",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "20",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "21",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
        {
            "id": "22",
            "name": "Rocky",
            "imgUrl": "https://i.ytimg.com/vi/XrIr7-WzoJU/maxresdefault.jpg",
            "status": "Czeka na spacer",
            "available": true,
            "gender": "Pies",
            "age": 1,
            "ownerName": "Andrzej Kowal",
            "sterilised": true,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "town": "Krakow",
            "ownerId": 1
        },
    ];
}
